name: 'threadit-api: continuous integration (pull requests)'

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: 'threadit-api: continuous integration (pull requests)'
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: threadit
          POSTGRES_PASSWORD: threadit
          POSTGRES_DB: threadit
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    defaults:
      run:
        working-directory: ./threadit-api
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore -warnaserror
      - name: Test
        env:
          dbUser: threadit
          dbPassword: threadit
          dbHost: localhost:5432
          dbName: threadit
        run: dotnet test --no-restore --verbosity normal